M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Tue 23 Jan 2024 12:41:11 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-23T12:41:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.53Y-2.635
X2.53Y-5.205
X7.995Y-2.635
X7.995Y-5.205
M30
