name: "Build Windows Release"

on:
  workflow_dispatch:
  push:
    tags:
      - "misrc_capture-*"

env:
  ARCHIVE_NAME_WINDOWS: ${{ github.ref_name }}-win-x86_64.zip

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download pcm_extract v1.0.0
        run: |
          Invoke-WebRequest "https://github.com/namazso/pcm_extract/releases/download/v1.0.0/pcm_extract.exe" -OutFile .\pcm_extract.exe

      - name: Create binary archive
        run: |
          # Create bundle directory and gather all pre-built files
          New-Item -ItemType Directory -Path .\bundle -Force
          
          # Copy pre-built Windows binaries
          Copy-Item .\windows-binaries\* .\bundle\ -Force
          
          # Copy pcm_extract.exe
          if (Test-Path ".\pcm_extract.exe") {
            Copy-Item .\pcm_extract.exe .\bundle\
          }
          
          # List what we have
          Get-ChildItem .\bundle\
          
          # Create the archive with all files
          Compress-Archive -Path .\bundle\* -DestinationPath ${{ env.ARCHIVE_NAME_WINDOWS }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: misrc_capture-windows
          path: ${{ env.ARCHIVE_NAME_WINDOWS }}
          if-no-files-found: error
